name: localizations_sdk_scripts
description: A tool for managing Flutter localizations
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  

dev_dependencies:
  yaml: ^3.1.3
  analyzer: ^7.3.0
  path: ^1.9.0
